doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # Keep DB session settings aligned with app behavior.
        options:
            1002: "SET time_zone = '+01:00', SESSION sql_mode = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

    orm:
        # True in dev, false in prod.
        auto_generate_proxy_classes: '%kernel.debug%'
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true

        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
