when@dev:
    web_profiler:
        toolbar: false

    framework:
        profiler:
            # Serializer profiling is expensive in large dev containers on Windows.
            collect_serializer_data: false

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
